//Tome of Knowledge
mods.extendedcrafting.TableCrafting.addShaped("tomeofknowledge", <item:projecte:tome>, [
    [<item:avaritia:infinity_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:projectex:fading_matter>, <item:projectex:fading_matter>, <item:projectex:fading_matter>, <item:projectex:fading_matter>, <item:projectex:fading_matter>, <item:extendedcrafting:the_ultimate_ingot>, <item:avaritia:infinity_ingot>], 
    [<item:extendedcrafting:the_ultimate_ingot>, <item:avaritia:infinity_ingot>, <item:projectex:final_star_shard>, <item:mekanism:crystal_osmium>, <item:mekanism:crystal_osmium>, <item:mekanism:crystal_osmium>, <item:projectex:final_star_shard>, <item:avaritia:infinity_ingot>, <item:extendedcrafting:the_ultimate_ingot>], 
    [<item:projectex:fading_matter>, <item:projectex:final_star_shard>, <item:avaritia:infinity_ingot>, <item:mekanism:creative_energy_cube>.withTag({mekData: {EnergyContainers: [{Container: 0 as byte, stored: "18446744073709551615.9999" as string}]}}), <item:mekanism:creative_fluid_tank>, <item:mekanism:creative_chemical_tank>, <item:avaritia:infinity_ingot>, <item:projectex:final_star_shard>, <item:projectex:fading_matter>], 
    [<item:projectex:fading_matter>, <item:mekanism:crystal_gold>, <item:bloodmagic:activationcrystalcreative>, <item:avaritia:infinity_catalyst>, <item:astralsorcery:shifting_star_vicio>, <item:avaritia:infinity_catalyst>, <item:create:creative_blaze_cake>, <item:mekanism:crystal_lead>, <item:projectex:fading_matter>], 
    [<item:projectex:fading_matter>, <item:mekanism:crystal_gold>, <item:botania:creative_pool>, <item:mahoutsukai:mana_circuit_magitech>, <item:projecte:transmutation_tablet>, <item:mahoutsukai:mana_circuit_magitech>, <item:createaddition:creative_energy>, <item:mekanism:crystal_lead>, <item:projectex:fading_matter>], 
    [<item:projectex:fading_matter>, <item:mekanism:crystal_gold>, <item:appliedenergistics2:creative_energy_cell>, <item:avaritia:infinity_catalyst>, <item:astralsorcery:shifting_star_aevitas>, <item:avaritia:infinity_catalyst>, <item:create:creative_motor>, <item:mekanism:crystal_lead>, <item:projectex:fading_matter>], 
    [<item:projectex:fading_matter>, <item:projectex:final_star_shard>, <item:avaritia:infinity_ingot>, <item:refinedstorage:creative_fluid_storage_disk>, <item:refinedstorage:creative_storage_disk>, <item:refinedstorage:creative_controller>, <item:avaritia:infinity_ingot>, <item:projectex:final_star_shard>, <item:projectex:fading_matter>], 
    [<item:extendedcrafting:the_ultimate_ingot>, <item:avaritia:infinity_ingot>, <item:projectex:final_star_shard>, <item:mekanism:crystal_uranium>, <item:mekanism:crystal_uranium>, <item:mekanism:crystal_uranium>, <item:projectex:final_star_shard>, <item:avaritia:infinity_ingot>, <item:extendedcrafting:the_ultimate_ingot>], 
    [<item:avaritia:infinity_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:projectex:fading_matter>, <item:projectex:fading_matter>, <item:projectex:fading_matter>, <item:projectex:fading_matter>, <item:projectex:fading_matter>, <item:extendedcrafting:the_ultimate_ingot>, <item:avaritia:infinity_ingot>]]); 

//Philosopophers Stone
craftingTable.removeByName("projecte:philosophers_stone");
craftingTable.removeByName("projecte:philosophers_stone_alt");
mods.extendedcrafting.TableCrafting.addShaped("philo", <item:projecte:philosophers_stone>, [
    [<item:botania:life_essence>, <item:botania:life_essence>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:botania:life_essence>, <item:botania:life_essence>], 
    [<item:botania:life_essence>, <item:projecte:red_matter>, <item:astralsorcery:resonating_gem>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:crystaltine_catalyst>, <item:astralsorcery:resonating_gem>, <item:projecte:red_matter>, <item:botania:life_essence>], 
    [<item:extendedcrafting:redstone_ingot>, <item:astralsorcery:resonating_gem>, <item:astralsorcery:resonating_gem>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:astralsorcery:resonating_gem>, <item:astralsorcery:resonating_gem>, <item:extendedcrafting:redstone_ingot>], 
    [<item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:crystaltine_catalyst>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:redstone_ingot>], 
    [<item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:crystaltine_catalyst>, <item:avaritia:neutronium_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:avaritia:endest_pearl>, <item:extendedcrafting:crystaltine_ingot>, <item:avaritia:neutronium_ingot>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:redstone_ingot>], 
    [<item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:crystaltine_catalyst>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:redstone_ingot>], 
    [<item:extendedcrafting:redstone_ingot>, <item:astralsorcery:resonating_gem>, <item:astralsorcery:resonating_gem>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:avaritia:neutronium_ingot>, <item:astralsorcery:resonating_gem>, <item:astralsorcery:resonating_gem>, <item:extendedcrafting:redstone_ingot>], 
    [<item:minecraft:air>, <item:projecte:red_matter>, <item:astralsorcery:resonating_gem>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:crystaltine_catalyst>, <item:extendedcrafting:crystaltine_catalyst>, <item:astralsorcery:resonating_gem>, <item:projecte:red_matter>, <item:minecraft:air>],
    [<item:minecraft:air>, <item:minecraft:air>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:extendedcrafting:redstone_ingot>, <item:minecraft:air>, <item:minecraft:air>]]); 

//Transmutation Table
craftingTable.removeByName("projecte:transmutation_table");
mods.extendedcrafting.TableCrafting.addShaped("TransmutationT", <item:projecte:transmutation_table>, [
    [<item:projecte:red_matter_block>, <item:projecte:red_matter_block>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:projecte:red_matter_block>, <item:projecte:red_matter_block>], 
    [<item:projecte:red_matter_block>, <item:projectex:violet_matter>, <item:mythicbotany:alfsteel_ingot>, <item:avaritia:neutronium_block>, <item:avaritia:neutronium_block>, <item:avaritia:neutronium_block>, <item:mythicbotany:alfsteel_ingot>, <item:projectex:violet_matter>, <item:projecte:red_matter_block>], 
    [<item:extendedcrafting:crystaltine_ingot>, <item:mythicbotany:alfsteel_ingot>, <item:mythicbotany:alfsteel_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:mythicbotany:alfsteel_ingot>, <item:mythicbotany:alfsteel_ingot>, <item:extendedcrafting:crystaltine_ingot>], 
    [<item:extendedcrafting:crystaltine_ingot>, <item:avaritia:neutronium_block>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:endest_pearl>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutronium_block>, <item:extendedcrafting:crystaltine_ingot>], 
    [<item:extendedcrafting:crystaltine_ingot>, <item:avaritia:neutronium_block>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:endest_pearl>, <item:projecte:philosophers_stone>, <item:avaritia:endest_pearl>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutronium_block>, <item:extendedcrafting:crystaltine_ingot>], 
    [<item:extendedcrafting:crystaltine_ingot>, <item:avaritia:neutronium_block>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:endest_pearl>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:neutronium_block>, <item:extendedcrafting:crystaltine_ingot>], 
    [<item:extendedcrafting:crystaltine_ingot>, <item:mythicbotany:alfsteel_ingot>, <item:mythicbotany:alfsteel_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:mythicbotany:alfsteel_ingot>, <item:mythicbotany:alfsteel_ingot>, <item:extendedcrafting:crystaltine_ingot>], 
    [<item:projecte:red_matter_block>, <item:projectex:violet_matter>, <item:mythicbotany:alfsteel_ingot>, <item:avaritia:neutronium_block>, <item:avaritia:neutronium_block>, <item:avaritia:neutronium_block>, <item:mythicbotany:alfsteel_ingot>, <item:projectex:violet_matter>, <item:projecte:red_matter_block>],
    [<item:projecte:red_matter_block>, <item:projecte:red_matter_block>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:extendedcrafting:crystaltine_ingot>, <item:projecte:red_matter_block>, <item:projecte:red_matter_block>]]); 

//Transmutation Tablet
craftingTable.removeByName("projecte:transmutation_tablet");
mods.extendedcrafting.TableCrafting.addShaped("TransmutationTA", <item:projecte:transmutation_tablet>, [
    [<item:projecte:klein_star_omega>, <item:projecte:klein_star_omega>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:projecte:klein_star_omega>, <item:projecte:klein_star_omega>], 
    [<item:projecte:klein_star_omega>, <item:projectex:cyan_matter>, <item:botania:gaia_ingot>, <item:appliedenergistics2:quantum_entangled_singularity>, <item:appliedenergistics2:quantum_entangled_singularity>, <item:appliedenergistics2:quantum_entangled_singularity>, <item:botania:gaia_ingot>, <item:projectex:cyan_matter>, <item:projecte:klein_star_omega>], 
    [<item:extendedcrafting:the_ultimate_ingot>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:extendedcrafting:the_ultimate_ingot>], 
    [<item:extendedcrafting:the_ultimate_ingot>, <item:appliedenergistics2:quantum_entangled_singularity>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix>, <item:projectex:green_matter>, <item:avaritia:crystal_matrix>, <item:avaritia:crystal_matrix_ingot>, <item:appliedenergistics2:quantum_entangled_singularity>, <item:extendedcrafting:the_ultimate_ingot>], 
    [<item:extendedcrafting:the_ultimate_ingot>, <item:appliedenergistics2:quantum_entangled_singularity>, <item:avaritia:crystal_matrix_ingot>, <item:projectex:green_matter>, <item:projecte:transmutation_table>, <item:projectex:green_matter>, <item:avaritia:crystal_matrix_ingot>, <item:appliedenergistics2:quantum_entangled_singularity>, <item:extendedcrafting:the_ultimate_ingot>], 
    [<item:extendedcrafting:the_ultimate_ingot>, <item:appliedenergistics2:quantum_entangled_singularity>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix>, <item:projectex:green_matter>, <item:avaritia:crystal_matrix>, <item:avaritia:crystal_matrix_ingot>, <item:appliedenergistics2:quantum_entangled_singularity>, <item:extendedcrafting:the_ultimate_ingot>], 
    [<item:extendedcrafting:the_ultimate_ingot>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:avaritia:crystal_matrix_ingot>, <item:botania:gaia_ingot>, <item:botania:gaia_ingot>, <item:extendedcrafting:the_ultimate_ingot>], 
    [<item:projecte:klein_star_omega>, <item:projectex:cyan_matter>, <item:botania:gaia_ingot>, <item:appliedenergistics2:quantum_entangled_singularity>, <item:appliedenergistics2:quantum_entangled_singularity>, <item:appliedenergistics2:quantum_entangled_singularity>, <item:botania:gaia_ingot>, <item:projectex:cyan_matter>, <item:projecte:klein_star_omega>],
    [<item:projecte:klein_star_omega>, <item:projecte:klein_star_omega>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:extendedcrafting:the_ultimate_ingot>, <item:projecte:klein_star_omega>, <item:projecte:klein_star_omega>]]);